name: truckbill
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: 3.29.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_hooks: ^0.20.5
  injectable: ^2.5.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  firebase_core: ^3.12.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  hooked_bloc: ^1.6.0
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
  cloud_firestore: ^5.6.5
  flutter_svg: ^2.0.17
  intl: ^0.19.0
  intl_utils: ^2.8.10
  flutter_localizations:
    sdk: flutter
  dartz: ^0.10.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  go_router_builder: ^2.8.1
  injectable_generator: ^2.7.0
  build_runner: ^2.4.15
  freezed: ^3.0.2
  json_serializable: ^6.9.4

flutter_intl:
  enabled: true
  main_locale: pl
  use_deferred_loading: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
