name: truckbill
environment:
  sdk: ">=3.7.0 <4.0.0"
  
dev_dependencies:
  melos: ^6.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  go_router_builder: ^2.8.1
  injectable_generator: ^2.7.0
  build_runner: ^2.4.15
  freezed: ^3.0.2
  json_serializable: ^6.9.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_hooks: ^0.20.5
  injectable: ^2.5.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  firebase_core: ^3.12.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  hooked_bloc: ^1.6.0
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
